Vagrant.configure("2") do |config|

    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/focal64"
      vm1.vm.hostname = "the-vm1"
      vm1.vm.network "forwarded_port", guest: 80, host: 8888
      vm1.vm.provision "shell", path: "vm1.sh"
      vm1.vm.provider "virtualbox" do |vbox1|
         vbox1.memory = 1024
         vbox1.cpus = 1
      end
    end

    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/focal64"
      vm2.vm.hostname = "the-vm2"
      vm2.vm.provision "shell", path: "vm2.sh"
      vm2.vm.provider :virtualbox do |vbox2|
         vbox2.memory = 1024
         vbox2.cpus = 1
      end
    end
end